name: Feature_engineering_pipeline

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ runs at the top of every hour (UTC)
  workflow_dispatch:      # 🟢 allows manual trigger

jobs:
  run-inference:
    runs-on: ubuntu-latest

    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}

    steps:
      - name: ⬇Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Inference Pipeline
        run: python scripts/feature_engineering.py
