name: inference_pipeline

on:
  workflow_run:
    workflows: ["Feature Engineering Pipeline"]  # 👈 match exactly with your feature_engineering.yml
    types:
      - completed

  workflow_dispatch:  # 👈 allow manual runs from GitHub UI

jobs:
  run-inference:
    runs-on: ubuntu-latest

    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}

    steps:
      - name: ⬇Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Inference Pipeline
        run: python scripts/feature_engineering.py
